name: PaoQueijo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instalar dependências
      run: npm install

    - name: Verificar estrutura da pasta PaoQueijo
      run: ls PaoQueijo

    - name: Iniciar servidor (modo teste)
      run: |
        node Server.js &
        sleep 5
        curl -I http://localhost:3000/PaoQueijo.html || echo "Servidor não respondeu"

    - name: Finalizar
      run: echo "Workflow concluído para Pão de Queijo"
